### ISSUE TITLE
Failing to parse non-existent certificates on Mac OS

### ISSUE THREAD

**Issue by bouncepaw** [crossbowerbt/dillo-plus#17]
I am running Mac OS Big Sur on MacBook Air M1 2020. See https://github.com/crossbowerbt/dillo-plus/issues/11#issuecomment-1646793024 for more details on how I built Dillo+.

Whatever website I open, Dillo+ complains on failing to parse some certificates.
```
Failed to parse certificates from /etc/ssl/certs/ca-certificates.crt
Failed to parse certificates from /etc/pki/tls/certs/ca-bundle.crt
Failed to parse certificates from /usr/share/ssl/certs/ca-bundle.crt
Failed to parse certificates from /usr/local/share/certs/ca-root.crt
Loaded TLS certificates.
```

Running `file` on these files tells that that they simply do not exist. Well, it makes sense for Dillo+ to not be able to parse them. But why does it try to? Is that a bug?

See the terminal printout:
=> https://gist.github.com/bouncepaw/2bb2a907a475fd2d4e604c978bbece16

**Comment by crossbowerbt** [comment]
Is not a bug, but is a bit verbose (needlessy so).
I'll reduce the output in the next release

**Comment by crossbowerbt** [comment]
I've grouped the messages into a single one, so the output is less confusing.
