### ISSUE TITLE
Could you merge the fixes made at https://github.com/rodarima/dillo ?

### ISSUE THREAD

**Issue by xplshn** [crossbowerbt/dillo-plus#19]
That's it, could you merge the fixes and commits from https://github.com/rodarima/dillo ?

**Comment by crossbowerbt** [comment]
hello @xplshn i'll try to merge some of the changes (such as the user agent for wget, maybe configurable from the config), and others...

If you have a list of the most important changes please post it here and i'll try to include it.

See ya!

**Comment by xplshn** [comment]
Thx! Does Dillo+ support these? https://github.com/rodarima/dillo/commit/3e00bcbe563418be7322795bf72076dfe313817f

That would be the most important addition, the other are outdated and I guess you've implemented most things they have too.

**Comment by crossbowerbt** [comment]
I've merged the thead-tfoot commits, and the user agent for the download DPI (with some modifies to read the user agent from configs):
- https://github.com/crossbowerbt/dillo-plus/commit/cd79a7fd6ce465e39be2d5e866d6c8b6d681b88e
- https://github.com/crossbowerbt/dillo-plus/commit/1ec20de36eb822143bb6ce1abad70e23f6fdf6f2

Thanks @xplshn, i'm closing the issue for now

**Comment by xplshn** [comment]
Thank you! This is so cool
