### ISSUE TITLE
update upstream url

### ISSUE THREAD

**Issue by Jan69** [crossbowerbt/dillo-plus#24]
update upstream url, dillo.org -> dillo-browser.github.io (or https://dillo-browser.github.io/old/ for compatibility with old links when needed)
dillo.org is no longer under the developers control (https://github.com/dillo-browser/dillo/), and has pages with spam (https://dillo.org/category/technology/) and many pages are simply missing

**Comment by Jan69** [comment]
if not the github version, then at least use archive.org snapshot, since the "live" website is clearly broken, and spam-pages don't inspire confidence either

**Comment by crossbowerbt** [comment]
Thanks for reporting the issue.

Urls have been changed to new websites with commit: https://github.com/crossbowerbt/dillo-plus/commit/582eb9e09b83626c3d976c3f3bff099c33e32850

Closing this.
