### ISSUE TITLE
Missing dependencies (debian-based)

### ISSUE THREAD

**Issue by Paculino** [crossbowerbt/dillo-plus#26]
Hello, this may not be the case on other systems, but on Debian-based systems at least (I am on Devuan 5 migrated from Debian 12), the list of dependencies is inadequate.

Dependencies I had to install on an amd64 system (including the dependencies which did not conflict with other packages) were:
**libiconv-hook1:amd64**
libfltk-forms1.3:amd64
libfltk-images1.3:amd64
fluid:amd64
libfltk-cairo1.3:amd64
**libfltk1.3-dev:amd64**
**libglx-dev:amd64**
**libgl-dev:amd64**
**libopengl-dev:amd64**
libglu1-mesa-dev:amd64
**libssl-dev:amd64**
**libxrender-dev:amd64**
libxfixes-dev:amd64
**libxcursor-dev:amd64**
**libxext-dev:amd64**
**libxinerama-dev:amd64
libfontconfig1-dev:amd64
**libxft-dev:amd64**
**libfontconfig-dev:amd64**

The last four I had some trouble with, so installed with `apt download` and `dpkg --force-all -i *.deb` when in the directory I was installing from. I also already had dillo installed from the OS repo, so that may have taken care of some packages. This isn't really a problem, since the errors when running `make install` will show what needs installed (or at least searched for with `apt find`), but it might be helpful to include them in the build dependencies. I bolded the ones which threw errors leading to the correction.

**Comment by crossbowerbt** [comment]
Fixed with https://github.com/crossbowerbt/dillo-plus/commit/e463b326df11eee1273921d3e4d60b7351c4b35f
