### ISSUE TITLE
STDERR errors

### ISSUE THREAD

**Issue by Veraellyunjie** [crossbowerbt/dillo-plus#34]
I have `dillo` installed from packages and I have just compiled `dillo-plus`.
`dillo` from packages:
```
> dillo
dillo_dns_init: Here we go! (threaded)
Disabling cookies.
Nav_open_url: new url='about:splash'
a_Dicache_cleanup: length = 0
```
`dillo-plus`:
```
/tmp/dillo-plus (main)> mv Makefile.options{,._}
/tmp/dillo-plus (main)> mv Makefile.options{.OpenBSD,}
/tmp/dillo-plus (main)> make
/tmp/dillo-plus (main)> ./src/dillo
Cannot open /usr/local/etc/dillo/dillorc: No such file or directoryRead error from /home/v11e/.dillo/dillorc: Bad file descriptorError closing files Bad file descriptorCannot open /usr/local/etc/dillo/bm.txt: No such file or directoryRead error from /home/v11e/.dillo/bm.txt: Bad file descriptorError closing files Bad file descriptorCannot open /usr/local/etc/dillo/keysrc: No such file or directoryRead error from /home/v11e/.dillo/keysrc: Bad file descriptorError closing files Bad file descriptorCannot open /usr/local/etc/dillo/domainrc: No such file or directoryRead error from /home/v11e/.dillo/domainrc: Bad file descriptorError closing files Bad file descriptordillo_dns_init: Here we go! (threaded)
Loaded TLS certificates.
Disabling cookies.
Cannot open /usr/local/etc/dillo/hsts_preload: No such file or directoryRead error from /home/v11e/.dillo/hsts_preload: Bad file descriptorError closing files Bad file descriptorNav_open_url: new url='about:splash'
 
```

1. missing newlines
2. `Cannot open /usr/local/etc/dillo/dillorc: No such file or directory`, `Cannot open /usr/local/etc/dillo/bm.txt: No such file or directory`, `Cannot open /usr/local/etc/dillo/keysrc: No such file or directory`, `Cannot open /usr/local/etc/dillo/domainrc: No such file or directory`, `Cannot open /usr/local/etc/dillo/hsts_preload: No such file or directory`
I guess, `/usr/local/etc` isn't used in OpenBSD at all - and I have several hundred packages installed:
```
> file /usr/local/etc
/usr/local/etc: cannot stat '/usr/local/etc' (No such file or directory)
```
whereas `> locate dillorc` shows `/etc/dillo/dillorc`.
3. `Read error from /home/v11e/.dillo/dillorc: Bad file descriptor`, `Read error from /home/v11e/.dillo/bm.txt: Bad file descriptor`, `Read error from /home/v11e/.dillo/keysrc: Bad file descriptor`, `Read error from /home/v11e/.dillo/domainrc: Bad file descriptor`, `Read error from /home/v11e/.dillo/hsts_preload: Bad file descriptor`
the files are empty - 0 bytes each:
```
> ll ~/.dillo
total 4
-rw-r--r--  1 v11e  v11e     0B Mar 19 19:21 bm.txt
-rw-------  1 v11e  v11e    13B Dec  6 22:42 cookiesrc
-rw-r--r--  1 v11e  v11e     0B Mar 19 19:21 dillorc
-rw-r--r--  1 v11e  v11e     0B Mar 19 19:21 domainrc
-rw-r--r--  1 v11e  v11e     0B Mar 19 19:21 hsts_preload
-rw-r--r--  1 v11e  v11e     0B Mar 19 19:21 keysrc
```

Upon 2nd and subsequent launch, those verbose errors are gone:
```
/tmp/dillo-plus (main)> ./src/dillo
dillo_dns_init: Here we go! (threaded)
Loaded TLS certificates.
Disabling cookies.
Nav_open_url: new url='about:splash'
	
```

**Comment by crossbowerbt** [comment]
Should be fixed with commit https://github.com/crossbowerbt/dillo-plus/commit/fdf2ae431bd9947fe2b91c126e52c8815bae4edf

Closing for now
