### ISSUE TITLE
dillo command name clash with original dillo

### ISSUE THREAD

**Issue by Veraellyunjie** [crossbowerbt/dillo-plus#35]
Makefile would install dillo-plus as `dillo`, so if a user has already original `dillo`, it would be overwritten.
I would expect dillo-plus to provide `dillo-plus` instead

**Comment by crossbowerbt** [comment]
Changed executable name to avoid conflicts with dillo https://github.com/crossbowerbt/dillo-plus/commit/1386f546b8c36d63bfd792658d8c38965bc6f7ff
